#
#Thu Mar 12 22:11:09 UYT 2026
acceptInsecureCerts=false
browserName=firefox
moz\:debuggerAddress=true
moz\:firefoxOptions={args\=[], log\={level\=error}, prefs\={devtools.chrome.enabled\=false, devtools.debugger.remote-enabled\=true, remote.active-protocols\=1}}
webSocketUrl=true
